import { Inter } from "next/font/google";
import Header from "@/app/components/header";
import Footer from "@/app/components/footer"
const interFontFamily = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={"interFontFamily.className" }>
      <body className="container">
        <Header/>
        <main>
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
